# This file stores configurations for your Shopify app.

scopes = "write_products,read_products,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_draft_orders,write_draft_orders,read_orders,write_orders,read_order_edits,write_order_edits,read_price_rules,write_price_rules"
